# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-codebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.3
      - name: Check go.mod file
        # ensure our go.mod file is clean
        run: |
          go mod tidy && git diff --exit-code || (echo "go.mod file is not clean. Run 'go mod tidy' locally and commit the changes" && exit 1)
      - name: Check Filenames
        run: scripts/check_filenames.sh
      - name: Check Formatting
        run: scripts/check_formatting.sh

  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version: 1.25.3
          - name: Get dependecies
            run: go get -v -t -d ./...
          - name: Build api
            run: go build -v .
          - name: Run unit tests
            run: go test -v ./...
          - name: Run linting checks
            uses: golangci/golangci-lint-action@v6
            with:
                version: v1.64
